---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: basestation-platform
type: Opaque
stringData:
  basestation-db: basestationdb
  basestation-user: postgres
  basestation-password: EGmwvjP56xV7iuKiC7Z8y4xgpz4XdhmT
  notification-db: notificationdb
  notification-user: postgres
  notification-password: guCGykTnRBrYKTqeW9GShXMbP6iQ8dwe
  auth-db: authdb
  auth-user: postgres
  auth-password: a2k3QeIpmymGwhksNP109KLvQmWE6tCb
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: basestation-platform
type: Opaque
stringData:
  username: admin
  password: NiatPcrSdcvGk2ubuWg3NIuFTWRmSLLy
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: basestation-platform
type: Opaque
stringData:
  username: admin
  password: FH7z3VLbbtQ6x0C1Y4q2V3jF7rtSR8nc
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: basestation-platform
type: Opaque
stringData:
  secret: vY0DEl+VSvp0atTkJ+m+mh+a3fm2qAAiZ7ZMcJ1IrLKzxKe9U2HAsf6MPfTbYNzTnvAWBlJ7ldqKPvCsdMu1Ag==
---
apiVersion: v1
kind: Secret
metadata:
  name: security-internal-secret
  namespace: basestation-platform
type: Opaque
stringData:
  secret: d07cb7f8500aeb8a5a43028d12eadeb86b4a917bc51993e282e1ec80d10aca18
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: basestation-platform
type: Opaque
stringData:
  password: dvb68mQHm8C04UTv9CxuehofiwL5ornM
